---
# Source: microfrontend/templates/gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.name }}
  namespace: microfront-uat
spec:
  selector:
    istio: ingress-private # usa el controlador predeterminado de Istio
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"