apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: microfront-uat
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    name: http-traffic
    port: 8080
    targetPort: 8080
  selector:
    app: {{ .Values.name }}
