# Default values for npmhello.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: arsbklogin

deployment:
  name: arsbklogin
  replicaCount: 1
  containerPort: 8091
  resources_limits_cpu: 1
  resources_limits_memory: 1Gi
  resources_requests_cpu: 500m
  resources_requests_memory: 500Mi

image:
  repository: azeastusbspdevnewobwcr.azurecr.io/arsbklogin
  pullPolicy: IfNotPresent
  tag: "0.0.2"


service:
  name: arsbklogin
  type: ClusterIP
  port: 8091


ingress:
  name: arsbklogin
  enabled: false
  path: /default
  port: 8091
  className: ""
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: ImplementationSpecific