name: CI Workflow
on:
  push:
  #   branches:
  #     - feature/devops1007
  #   # paths-ignore:
  #   #   - '.github/**'
  # pull_request:
  #   branches:
  #     - feature/devops1007
  #   # paths-ignore:
  #   #   - '.github/**'
 
env:
  AMBIENTE: dev
  # AMBIENTE: ${{ (github.ref == 'refs/heads/feature/devops1007' && 'dev') }}

jobs:

  # #SONAR
  # sonarqube:
  #   if: github.event_name == 'push'
  #   name: Npm quality gate workflow
  #   uses: santander-group-shared-assets/gln-workflows/.github/workflows/npm-quality-image.yml@v1
  #   secrets: inherit


  # #FORTIFY
  # fortify:
  #   if: github.event_name == 'push'
  #   name: Npm security workflow
  #   uses: santander-group-shared-assets/gln-workflows/.github/workflows/npm-security-image.yml@v1
  #   secrets: inherit



  #CONFIGURAR EL RUNNNER
  setup-env-vars:
    if: github.event_name == 'push'
    name: Setup environment variables
    uses: santander-group-gluon/gln-multipurpose-child-reusable-workflows/.github/workflows/setup-env-vars.yml@v1.2.0
    with:
      runner: npm-runner
      repo: ${{ github.repository }}
      repo-branch: ${{ github.ref }}
    secrets: inherit

  # COMPILAR EL PROYECTO CON MAVEN
  ci-build-npm:
    if: github.event_name == 'push'
    name: Build NPM
    runs-on: npm-runner
    needs: setup-env-vars
    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment ci/cd variables
        id: vars
        uses: ./.github/workflows/set-up-env
        with:
          ambiente: ${{ env.AMBIENTE }}
          repositorio: ${{ github.repository }}
      
      - name: Visualizar variables
        run: |
          echo "namespace=${{ env.namespace }}"
          echo "cluster_name=${{ env.cluster_name }}"
          echo "cluster_resource_group=${{ env.cluster_resource_group }}"
          echo "repositorio=${{ env.repositorio }}"
          echo "version=${{ env.tag }}"
          echo "container_port=${{ env.container_port }}"
          echo "container_path=${{ env.container_path }}"

      - name: Install dependencies
        run: npm install

      - name: Build        
        run: npm run build


      - name: Docker build
        run: |
          docker build \
            --file .github/Dockerfile \
            --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.repositorio }}:${{ env.tag }} .

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.repositorio }}:${{ env.tag }}

  #   outputs:
  #     tag: ${{ env.tag }}
  #     cluster_name: ${{ env.cluster_name }}
  #     cluster_resource_group: ${{ env.cluster_resource_group }}
  #     namespace: ${{ env.namespace }}
  #     repositorio: ${{ env.repositorio }}
  #     container_port: ${{ env.container_port }}
  #     container_path: ${{ env.container_path }}


  # deploy:
  #   if: github.event_name == 'push'
  #   needs: ci-build-npm
  #   uses: ./.github/workflows/cd.yaml
  #   secrets: inherit
  #   with:
  #     tag: ${{ needs.ci-build-npm.outputs.tag }}
  #     cluster_name: ${{ needs.ci-build-npm.outputs.cluster_name }}
  #     cluster_resource_group: ${{ needs.ci-build-npm.outputs.cluster_resource_group }}
  #     namespace: ${{ needs.ci-build-npm.outputs.namespace }}
  #     repositorio: ${{ needs.ci-build-npm.outputs.repositorio }}
  #     container_port: ${{ needs.ci-build-npm.outputs.container_port }}
  #     container_path: ${{ needs.ci-build-npm.outputs.container_path }}

