name: CI Workflow
on:
  push:
    branches:
      - release/**
    paths-ignore:
      - '.github/**'
 
 
env:
  AMBIENTE: uat

jobs:

  # #SONAR
  # sonarqube:
  #   if: github.event_name == 'push'
  #   name: Npm quality gate workflow
  #   uses: santander-group-shared-assets/gln-workflows/.github/workflows/npm-quality-image.yml@v1
  #   secrets: inherit


  #FORTIFY
  fortify:
    if: github.event_name == 'push'
    name: Npm security workflow
    uses: santander-group-shared-assets/gln-workflows/.github/workflows/npm-security-image.yml@v1
    secrets: inherit



  #CONFIGURAR EL RUNNNER
  setup-env-vars:
    # if: github.event_name == 'push'
    if: always()
    needs: [fortify]
    name: Setup environment variables
    uses: santander-group-gluon/gln-multipurpose-child-reusable-workflows/.github/workflows/setup-env-vars.yml@v1.2.0
    with:
      runner: npm-runner
      repo: ${{ github.repository }}
      repo-branch: ${{ github.ref }}
    secrets: inherit

  # COMPILAR EL PROYECTO CON MAVEN
  ci-build-npm:
    if: always()
    # if: github.event_name == 'push'
    name: Build NPM
    runs-on: npm-runner
    needs: setup-env-vars
    defaults:
      run:
        shell: bash

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment ci/cd variables
        id: vars
        uses: ./.github/actions/set-up-env
        with:
          ambiente: ${{ env.AMBIENTE }}
          repositorio: ${{ github.repository }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          npm install


      - name: Build        
        run: npm run build:uat


      - name: Docker build
        run: |
          docker build \
            --file .github/Dockerfile \
            --tag ${{ vars[env.registry_login_server] }}/${{ env.repositorio }}:${{ env.tag }} .

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars[env.registry_login_server] }}
          username: ${{ secrets[env.registry_username] }}
          password: ${{ secrets[env.registry_password] }}

      - run: |
          docker push ${{ vars[env.registry_login_server] }}/${{ env.repositorio }}:${{ env.tag }}

    outputs:
      tag: ${{ env.tag }}
      cluster_name: ${{ env.cluster_name }}
      cluster_resource_group: ${{ env.cluster_resource_group }}
      namespace: ${{ env.namespace }}
      repositorio: ${{ env.repositorio }}
      container_port: ${{ env.container_port }}
      container_path: ${{ env.container_path }}
      ambiente: ${{ env.AMBIENTE }}
      azure_credentials: ${{ env.azure_credentials }}
      registry_login_server: ${{ env.registry_login_server }}
      registry_username: ${{ env.registry_username }}
      registry_password: ${{ env.registry_password }}      


  deploy:
    # if: github.event_name == 'push'
    if: always()
    needs: ci-build-npm
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
    with:
      tag: ${{ needs.ci-build-npm.outputs.tag }}
      cluster_name: ${{ needs.ci-build-npm.outputs.cluster_name }}
      cluster_resource_group: ${{ needs.ci-build-npm.outputs.cluster_resource_group }}
      namespace: ${{ needs.ci-build-npm.outputs.namespace }}
      repositorio: ${{ needs.ci-build-npm.outputs.repositorio }}
      container_port: ${{ needs.ci-build-npm.outputs.container_port }}
      container_path: ${{ needs.ci-build-npm.outputs.container_path }}
      ambiente: ${{ needs.ci-build-npm.outputs.ambiente }}
      azure_credentials: ${{ needs.ci-build-npm.outputs.azure_credentials }}
      registry_login_server: ${{ needs.ci-build-npm.outputs.registry_login_server }}
      registry_username: ${{ needs.ci-build-npm.outputs.registry_username }}
      registry_password: ${{ needs.ci-build-npm.outputs.registry_password }}
