apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    name: http-traffic
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.containerPort }}
  selector:
    app: {{ .Values.name }}


