apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingress-private # usa el controlador predeterminado de Istio
  servers:
  - port:
      number: {{ .Values.istio.port }}
      name: http
      protocol: HTTP
    hosts:
    - "*"