apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.name }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.path }}
    route:
    - destination:
        host: {{ .Values.name }}
        port:
          number: {{ .Values.service.port }}